### ISSUE TITLE
--loglevel should be --log-level

### ISSUE THREAD

**Issue by jonsterling** [alephcloud/hs-yet-another-logger#14]
I can submit a pull request to this effect soon.

**Comment by larskuhtz** [comment]
Cool. 

I wonder if we should keep the current version as deprecated legacy syntax around (possible hidden in the output of --help)? Not sure if it's worth though.

**Comment by jonsterling** [comment]
I guess it would depend on whether anybody is using this package yet for anything where someone depends on the old syntax...

**Comment by larskuhtz** [comment]
I use yet-another-logger in a few places in other packages, but I don't think that I have code depending on this syntax. Also I don't think anyone else depends on it. Yet, probably we should increase the second level version number if we remove the old syntax. I think it's fine.

**Comment by larskuhtz** [comment]
Solved in PR #21
